stages:
  - deploy

variables:
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"

before_script:
  - apt-get update && apt-get install -y curl
  - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
  - apt-get install -y nodejs
  - npm install -g serverless
  - serverless plugin install -n serverless-dotenv-plugin
  - serverless plugin install -n serverless-offline
  - serverless plugin install -n serverless-go-build

deploy_dev:
  stage: deploy
  image: golang:latest
  script:
    - go version
    - export BUCKET_NAME=$BUCKET_NAME_DEV
    - serverless build
    - serverless deploy --stage dev
  only:
    - dev

deploy_prod:
  stage: deploy
  image: golang:latest
  script:
    - go version
    - export BUCKET_NAME=$BUCKET_NAME_PROD
    - serverless build
    - serverless deploy --stage production
  only:
    - master
