stages:
  - build
  - deploy

build:
  stage: build
  image: golang:1.16
  script:
    - go mod download
    - go build -o promatch-view-user ./cmd/user/promatch-view-user/main.go
    - go build -o promatch-create-user ./cmd/user/promatch-create-user/main.go
  artifacts:
    paths:
      - promatch-view-user
      - promatch-create-user

deploy:
  stage: deploy
  image: node:14
  before_script:
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
    - apt-get install -y nodejs
    - npm install -g serverless
  script:
    - serverless deploy --stage production
  only:
    - master
