stages:
  - build
  - deploy
variables:
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"

before_script:
  - apt-get update && apt-get install -y curl
  - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
  - apt-get install -y nodejs
  - npm install -g serverless
  - serverless plugin install -n serverless-dotenv-plugin
  - serverless plugin install -n serverless-offline
  - serverless plugin install -n serverless-go-build

build:
  stage: build
  image: golang:latest 
  script:
    - go version 
    - serverless build
  
deploy_dev:
  stage: deploy
  image: node:18
  script:
    - serverless deploy --stage dev
  only:
    - dev

deploy_prod:
  stage: deploy
  image: node:18
  script:
    - serverless deploy --stage production
  only:
    - master
