service: motion

provider:
  name: aws
  runtime: go1.x
  region: us-east-2


plugins:
  - serverless-dotenv-plugin
useDotenv: true


custom:
  motionEnvironment:
    DBPASS: ${env:DBPASS}
    DBUSER: ${env:DBUSER}


functions:
  motion-view-user:
    handler: motion-view-user/main
    events:
      - http:
          path: /users
          method: get
          cors: true
    environment: ${self:custom.motionEnvironment}

  motion-create-user:
    handler: motion-create-user/main
    events:
      - http:
          path: /users
          method: post
          cors: true
    environment: ${self:custom.motionEnvironment}
