service: promatch

provider:
  name: aws
  runtime: go1.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-go-build
  - serverless-offline
  - serverless-dotenv-plugin
useDotenv: true

custom:
  promatchEnvironment:
    DBPASS: ${env:DBPASS}
    DBUSER: ${env:DBUSER}
  go-build:
    awsbuildPrefix: "GOOS=linux GOARCH=amd64 CGO_ENABLED=0 "
    binPath: "build"

functions:
  view-user:
    handler: cmd/user/promatch-view-user/main.go
    events:
      - http:
          path: /users
          method: get
          cors: true
    environment: ${self:custom.promatchEnvironment}

  create-user:
    handler: cmd/user/promatch-create-user/main.go
    events:
      - http:
          path: /users
          method: post
          cors: true
    environment: ${self:custom.promatchEnvironment}

  update-user:
    handler: cmd/user/promatch-update-user/main.go
    events:
      - http:
          path: /users
          method: put
          cors: true
    environment: ${self:custom.promatchEnvironment}

  delete-user:
    handler: cmd/user/promatch-delete-user/main.go
    events:
      - http:
          path: /users
          method: delete
          cors: true
    environment: ${self:custom.promatchEnvironment}


  create-auth-token:
    handler: cmd/auth/promatch-create-auth-token/main.go
    events:
      - http:
          path: /auth
          method: post
          cors: true
    environment: ${self:custom.promatchEnvironment}

  delete-auth-token:
    handler: cmd/auth/promatch-delete-auth-token/main.go
    events:
      - http:
          path: /auth
          method: delete
          cors: true
    environment: ${self:custom.promatchEnvironment}

  login-user:
    handler: cmd/login/promatch-login-user/main.go
    events:
      - http:
          path: /login
          method: post
          cors: true
    environment: ${self:custom.promatchEnvironment}
