service: promatch

provider:
  name: aws
  runtime: go1.x
  region: us-east-2

plugins:
  - serverless-go-build
  - serverless-offline
  - serverless-dotenv-plugin
useDotenv: true

custom:
  promatchEnvironment:
    DBPASS: ${env:DBPASS}
    DBUSER: ${env:DBUSER}
  go-build:
    awsbuildPrefix: "GOOS=linux GOARCH=amd64 CGO_ENABLED=0 "
    buildCmd: go build -o %2 %1
    binPath: ""

functions:
  promatch-view-user:
    handler: cmd/user/promatch-view-user/main.go
    events:
      - http:
          path: /users
          method: get
          cors: true
    environment: ${self:custom.promatchEnvironment}
    logGroupName: /aws/lambda/promatchstaging-view-user

  promatch-create-user:
    handler: cmd/user/promatch-create-user/main.go
    events:
      - http:
          path: /users
          method: post
          cors: true
    environment: ${self:custom.promatchEnvironment}
    logGroupName: /aws/lambda/promatchstaging-create-user

  promatch-create-auth-token:
    handler: cmd/auth/promatch-create-auth-token/main.go
    events:
      - http:
          path: /auth
          method: post
          cors: true
    environment: ${self:custom.promatchEnvironment}
    logGroupName: /aws/lambda/promatchstaging-create-auth-token

  promatch-delete-auth-token:
    handler: cmd/auth/promatch-delete-auth-token/main.go
    events:
      - http:
          path: /auth
          method: delete
          cors: true
    environment: ${self:custom.promatchEnvironment}
    logGroupName: /aws/lambda/promatchstaging-delete-auth-token

  promatch-login-user:
    handler: cmd/login/promatch-login-user/main.go
    events:
      - http:
          path: /login
          method: post
          cors: true
    environment: ${self:custom.promatchEnvironment}
    logGroupName: /aws/lambda/promatchstaging-login-user.go
