service: motion

provider:
  name: aws
  runtime: go1.x
  region: us-east-2

functions:
  motion-view-user:
    handler: motion-view-user/main
    events:
      - http:
          path: /users
          method: get
          cors: true
    environment:
      DBPASS: 
      DBUSER: 

  motion-create-user:
    handler: motion-create-user/main
    events:
      - http:
          path: /users
          method: post
          cors: true
    environment:
      DBPASS: 
      DBUSER: 
